#
# Copyrigh 2011 Grigale Ltd. All rights reserved.
# Use is subject to license terms.
#
.KEEP_STATE:

ON_SRC          = /data/opensolaris/onnv-gate
EXTRA_INCLUDES	=

# Utilities
CP		= cp
MKDIR           = mkdir

# Global definitions
MACH_32		=
MACH_64		= -m64
C99MODE		= -xc99=%all
DEBUG		= -g -xO0
KERNEL		= -D_KERNEL
INCLUDES	= -I./include $(EXTRA_INCLUDES)
CFLAGS		= -v $(DEBUG) $(C99MODE) $(INCLUDES)

LDFLAGS		=
LINTFLAGS	= $(KERNEL) $(INCLUDES) -errsecurity=extended -Nlevel

